apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-script
data:
  init-db.js: |
    // Switch to the microservices database
    db = db.getSiblingDB('microservices_db');

    

    

    // Create orders collection and insert sample data
    db.orders.insertMany([
      {
        _id: ObjectId(),
        id: 1,
        userId: 1,
        items: [
          { productId: 1, quantity: 1, price: 1299.99 },
          { productId: 2, quantity: 2, price: 29.99 }
        ],
        totalAmount: 1359.97,
        status: "completed",
        orderDate: new Date("2025-01-15T10:30:00Z"),
        shippingAddress: {
          street: "123 Main St",
          city: "New York",
          state: "NY",
          zipCode: "10001",
          country: "USA"
        },
        createdAt: new Date("2025-01-15T10:30:00Z"),
        updatedAt: new Date("2025-01-16T10:30:00Z")
      },
      {
        _id: ObjectId(),
        id: 2,
        userId: 2,
        items: [
          { productId: 3, quantity: 1, price: 299.99 }
        ],
        totalAmount: 299.99,
        status: "pending",
        orderDate: new Date("2025-01-20T14:15:00Z"),
        shippingAddress: {
          street: "456 Oak Ave",
          city: "Los Angeles",
          state: "CA",
          zipCode: "90210",
          country: "USA"
        },
        createdAt: new Date("2025-01-20T14:15:00Z"),
        updatedAt: new Date("2025-01-20T14:15:00Z")
      },
      {
        _id: ObjectId(),
        id: 3,
        userId: 3,
        items: [
          { productId: 4, quantity: 3, price: 89.99 },
          { productId: 5, quantity: 1, price: 199.99 }
        ],
        totalAmount: 469.96,
        status: "processing",
        orderDate: new Date("2025-01-22T09:45:00Z"),
        shippingAddress: {
          street: "789 Pine Rd",
          city: "Chicago",
          state: "IL",
          zipCode: "60601",
          country: "USA"
        },
        createdAt: new Date("2025-01-22T09:45:00Z"),
        updatedAt: new Date("2025-01-22T11:30:00Z")
      },
      {
        _id: ObjectId(),
        id: 4,
        userId: 1,
        items: [
          { productId: 6, quantity: 2, price: 49.99 },
          { productId: 7, quantity: 1, price: 129.99 },
          { productId: 8, quantity: 4, price: 15.99 }
        ],
        totalAmount: 293.94,
        status: "shipped",
        orderDate: new Date("2025-01-25T16:20:00Z"),
        shippingAddress: {
          street: "321 Elm St",
          city: "Miami",
          state: "FL",
          zipCode: "33101",
          country: "USA"
        },
        createdAt: new Date("2025-01-25T16:20:00Z"),
        updatedAt: new Date("2025-01-26T08:15:00Z")
      },
      {
        _id: ObjectId(),
        id: 5,
        userId: 4,
        items: [
          { productId: 9, quantity: 1, price: 899.99 }
        ],
        totalAmount: 899.99,
        status: "pending",
        orderDate: new Date("2025-01-28T13:10:00Z"),
        shippingAddress: {
          street: "654 Maple Dr",
          city: "Seattle",
          state: "WA",
          zipCode: "98101",
          country: "USA"
        },
        createdAt: new Date("2025-01-28T13:10:00Z"),
        updatedAt: new Date("2025-01-28T13:10:00Z")
      },
      {
        _id: ObjectId(),
        id: 6,
        userId: 2,
        items: [
          { productId: 10, quantity: 2, price: 39.99 },
          { productId: 11, quantity: 1, price: 79.99 },
          { productId: 12, quantity: 3, price: 24.99 }
        ],
        totalAmount: 234.95,
        status: "cancelled",
        orderDate: new Date("2025-02-01T11:30:00Z"),
        shippingAddress: {
          street: "987 Cedar Ln",
          city: "Austin",
          state: "TX",
          zipCode: "73301",
          country: "USA"
        },
        createdAt: new Date("2025-02-01T11:30:00Z"),
        updatedAt: new Date("2025-02-01T15:45:00Z")
      }
    ]);

    // Create indexes for better performance
    db.users.createIndex({ "id": 1 }, { unique: true });
    db.users.createIndex({ "email": 1 }, { unique: true });
    
    db.products.createIndex({ "id": 1 }, { unique: true });
    db.products.createIndex({ "sku": 1 }, { unique: true });
    db.products.createIndex({ "category": 1 });
    
    db.orders.createIndex({ "id": 1 }, { unique: true });
    db.orders.createIndex({ "userId": 1 });
    db.orders.createIndex({ "status": 1 });
    db.orders.createIndex({ "orderDate": 1 });

    print("Database initialization completed successfully!");
