apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  # Username: admin (base64 encoded)
  mongo-root-username: YWRtaW4=
  # Password: password123 (base64 encoded)
  mongo-root-password: cGFzc3dvcmQxMjM=
